### ISSUE TITLE
please update acl auth updates for conda-forge

### ISSUE THREAD

**Issue by Ji3jin** [ContinuumIO/libhdfs3-downstream#16]
I install libhdfs3 from conda-forge. Then I find it is not useful for acl auth.
the libhdfs3 on conda-forge is fork this repo.  [martindurant/libhdfs3-downstream](https://github.com/martindurant/libhdfs3-downstream)
can you update it please!

**Comment by martindurant** [comment]
I don't know your level of C++ coding, but the attempt to merge in the newer work from hawq, security from bdrosen96, extra functionality like concat and then the ACL fix resulted in a build that caused segfaults for some people, including my personal testing. If you can help merging int he changes to make a stable build, it would be massively appreciated.
Note that you can always build your own package from the sources either in this repo or in the fork at martindurant/.

**Comment by Ji3jin** [comment]
ok ， my level of c++ is low ，but I will have a try. thanks!
