### ISSUE TITLE
Build error on Fedora 26 (GCC 7.2.1)

### ISSUE THREAD

**Issue by ferristseng** [ContinuumIO/libhdfs3-downstream#5]
I was receiving the following build error on Fedora 26:

```
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is GNU 7.2.1
-- Check for working C compiler: /usr/lib64/ccache/gcc
-- Check for working C compiler: /usr/lib64/ccache/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/g++
-- Check for working CXX compiler: /usr/lib64/ccache/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMake/Platform.cmake:19 (LIST):
  LIST index: 1 out of range (-1, 0)
Call Stack (most recent call first):
  CMakeLists.txt:14 (INCLUDE)
```

This appears to be an issue with a change to how `-dumpversion` works. 

Running `-dumpversion` on Fedora 26 with GCC 7.2.1 gives:

```
$ gcc -dumpversion
7
```

Instead, https://github.com/ContinuumIO/libhdfs3-downstream/blob/7842951deab2db8f1c13519a2ac32330672e756a/libhdfs3/CMake/Platform.cmake#L10 can be changed to use `-dumpfullversion`, which gives the correct version number

```
$ gcc -dumpfullversion
7.2.1
```

I think changing the flag might break other builds, so I'm not really sure how to make the change, but I hope this helps anyone else having trouble building this.

**Comment by martindurant** [comment]
Thanks for pointing this out. Which any luck, some cmake expert will make the appropriate correction.

**Comment by sk1p** [comment]
With #11 merged this can now be closed (forgot to mention this issue in the pull request)

**Comment by martindurant** [comment]
Thanks.
